#!/bin/bash

# Pre-build Dockerfiles from env vars to be DRY

# only if outside of docker hub autobuild
# export DOCKER_REPO=tedmiston/automated-builds-test

source ./hooks/pre_build_one
source ./hooks/pre_build_two
